# Generated by Django 5.1.5 on 2025-04-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_rename_performer_to_executor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='labels',
        ),
    ]
